server.port: 8090
property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green



spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect